"""baseline schema

這是「現況基準」遷移，內容等同於先前 Base.metadata.create_all 建出來的
locations / daily_conditions 兩張表。

重要：正式環境（Supabase）與任何既有的本機 sea_conditions.db 都已經有這兩張表，
第一次導入 Alembic 前必須先對那些資料庫執行一次：

    alembic stamp 81e1c67e1b76

把版本標記寫進去、但不重建表。全新的空資料庫則不需要 stamp，直接
`alembic upgrade head` 會照這支遷移把表建好。詳見 DEPLOY.md。

Revision ID: 81e1c67e1b76
Revises:
Create Date: 2026-09-06 14:20:42.937269+08:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '81e1c67e1b76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=False),
    sa.Column('spots', sa.JSON(), nullable=False),
    sa.Column('activities', sa.JSON(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('cwa_marine_zone', sa.String(length=40), nullable=True),
    sa.Column('cwa_tide_station', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_slug'), ['slug'], unique=True)

    op.create_table('daily_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('wave_height_m', sa.Float(), nullable=True),
    sa.Column('wave_period_s', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('wind_scale', sa.Integer(), nullable=True),
    sa.Column('wind_dir', sa.String(length=8), nullable=True),
    sa.Column('gust_ms', sa.Float(), nullable=True),
    sa.Column('water_temp_c', sa.Float(), nullable=True),
    sa.Column('visibility_m', sa.Float(), nullable=True),
    sa.Column('tide_high', sa.String(length=40), nullable=True),
    sa.Column('tide_low', sa.String(length=40), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('rating_score', sa.Float(), nullable=True),
    sa.Column('rating_reasons', sa.JSON(), nullable=False),
    sa.Column('advice_text', sa.Text(), nullable=True),
    sa.Column('advice_model', sa.String(length=40), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'date', 'source', name='uq_condition_loc_date_source')
    )
    with op.batch_alter_table('daily_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_conditions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_conditions_location_id'), ['location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_conditions_location_id'))
        batch_op.drop_index(batch_op.f('ix_daily_conditions_date'))

    op.drop_table('daily_conditions')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_slug'))

    op.drop_table('locations')
    # ### end Alembic commands ###
