"""add spots table

Revision ID: 474f847fb5b2
Revises: 494e5460a629
Create Date: 2026-09-06 18:13:24.892390+08:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '474f847fb5b2'
down_revision: Union[str, None] = '494e5460a629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('coord_approx', sa.Boolean(), nullable=False),
    sa.Column('activities', sa.JSON(), nullable=False),
    sa.Column('bottom', sa.String(length=16), nullable=True),
    sa.Column('facing_deg', sa.Integer(), nullable=True),
    sa.Column('shelter', sa.String(length=12), nullable=True),
    sa.Column('level', sa.String(length=12), nullable=True),
    sa.Column('entry', sa.String(length=8), nullable=True),
    sa.Column('depth_min_m', sa.Float(), nullable=True),
    sa.Column('depth_max_m', sa.Float(), nullable=True),
    sa.Column('blurb', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spots_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spots_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spots_slug'))
        batch_op.drop_index(batch_op.f('ix_spots_location_id'))

    op.drop_table('spots')
    # ### end Alembic commands ###
