"""add wave_dir to daily_conditions

Revision ID: 494e5460a629
Revises: 81e1c67e1b76
Create Date: 2026-09-06 14:24:33.811255+08:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '494e5460a629'
down_revision: Union[str, None] = '81e1c67e1b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wave_dir', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_conditions', schema=None) as batch_op:
        batch_op.drop_column('wave_dir')

    # ### end Alembic commands ###
