"""台灣潛點 / 浪點固定清單（第二層 MVP）。

- LOCATIONS：地區（島或一段海岸），每個有一組經緯度，refresh 會逐一抓 Open-Meteo。
- SPOTS：地區底下的實際下水點，各有座標與靜態屬性（底質、朝向、遮蔽、程度…）。

`coord_approx=True` 代表座標是「以鄰近陸地地標推估」的（沈船、水下地形點、
或地名資料庫只查得到鄉鎮中心），上線前要用 Google Maps 逐一校正。
`facing_deg` 目前多半留空 —— 之後用海岸線外法線自動算。

活動別代碼：scuba 水肺 / freedive 自由潛水 / snorkel 浮潛 / surf 衝浪
底質 bottom：sand 沙 / reef 礁 / point 岬礁 / rivermouth 河口 / harbour 漁港內 / wreck 沈船 / artificial 人工魚礁 / mixed 混合
遮蔽 shelter：open 全開放 / semi 半遮蔽 / sheltered 遮蔽（灣內、港內）
程度 level：beginner 初 / intermediate 中 / advanced 進階
進出 entry：shore 岸潛 / boat 船潛
"""

from __future__ import annotations

# ─────────────────────────────  地區  ─────────────────────────────

LOCATIONS: list[dict] = [
    {
        "slug": "xiaoliuqiu",
        "name": "小琉球",
        "name_en": "Xiaoliuqiu (Lamay Island)",
        "region": "屏東 · 離島",
        "blurb": "全台最容易看到海龜的珊瑚礁島，全年可潛，適合初學者與浮潛。",
        "spots": ["花瓶岩", "美人洞", "厚石裙礁", "龍蝦洞", "杉福漁港"],
        "activities": ["scuba", "freedive", "snorkel"],
        "lat": 22.342,
        "lon": 120.377,
        "cwa_marine_zone": "臺灣海峽南部",
        "cwa_tide_station": "屏東縣琉球鄉",
    },
    {
        "slug": "lyudao",
        "name": "綠島",
        "name_en": "Green Island",
        "region": "臺東 · 離島",
        "blurb": "能見度極佳的火山島，硬珊瑚覆蓋率高，石朗、大白沙為熱門岸潛點。",
        "spots": ["石朗", "柴口", "大白沙", "大香菇", "鋼鐵礁"],
        "activities": ["scuba", "freedive", "snorkel"],
        "lat": 22.657,
        "lon": 121.492,
        "cwa_marine_zone": "臺灣東南部海面",
        "cwa_tide_station": "臺東縣綠島鄉",
    },
    {
        "slug": "lanyu",
        "name": "蘭嶼",
        "name_en": "Orchid Island",
        "region": "臺東 · 離島",
        "blurb": "黑潮流經、生態原始的離島，地形潛與大洋洄游魚種豐富，適合進階者。",
        "spots": ["玉女岩", "母雞岩", "開元港藍洞", "椰油斷層", "八代灣沈船"],
        "activities": ["scuba", "freedive"],
        "lat": 22.043,
        "lon": 121.539,
        "cwa_marine_zone": "臺灣東南部海面",
        "cwa_tide_station": "臺東縣蘭嶼鄉",
    },
    {
        "slug": "kenting-houbihu",
        "name": "墾丁 · 恆春半島",
        "name_en": "Kenting / Hengchun Peninsula",
        "region": "屏東 · 恆春半島",
        "blurb": "台灣潛水教學重鎮，後壁湖、萬里桐一帶珊瑚魚群豐富；南灣、佳樂水則是南部主力浪點。",
        "spots": ["後壁湖", "出水口", "萬里桐", "南灣", "佳樂水"],
        "activities": ["scuba", "freedive", "snorkel", "surf"],
        "lat": 21.960,
        "lon": 120.745,
        "cwa_marine_zone": "巴士海峽",
        "cwa_tide_station": "屏東縣恆春鎮",
    },
    {
        "slug": "longdong",
        "name": "東北角",
        "name_en": "Longdong / Northeast Coast",
        "region": "新北 · 東北角",
        "blurb": "北台灣最大岸潛場，四稜砂岩地形、灣內平靜；福隆則是穩定的沙灘浪點。",
        "spots": ["龍洞灣", "鼻頭角", "和美", "福隆"],
        "activities": ["scuba", "freedive", "surf"],
        "lat": 25.110,
        "lon": 121.922,
        "cwa_marine_zone": "臺灣北部海面",
        "cwa_tide_station": "新北市貢寮區",
    },
    {
        "slug": "beihaian",
        "name": "北海岸",
        "name_en": "North Coast",
        "region": "基隆 · 新北 · 北海岸",
        "blurb": "潮境、望海巷一帶是保育有成的軟珊瑚岸潛區；白沙灣、中角灣是離台北最近的入門浪點。",
        "spots": ["潮境公園", "望海巷", "龜吼", "白沙灣", "中角灣"],
        "activities": ["scuba", "freedive", "snorkel", "surf"],
        "lat": 25.200,
        "lon": 121.650,
        "cwa_marine_zone": "臺灣北部海面",
        "cwa_tide_station": "基隆市",
    },
    {
        "slug": "penghu",
        "name": "澎湖本島",
        "name_en": "Penghu Main Island",
        "region": "澎湖 · 本島",
        "blurb": "玄武岩地形與軟珊瑚聞名，夏季風平浪靜，山水一帶交通方便、適合入門。",
        "spots": ["山水", "杭灣"],
        "activities": ["scuba", "freedive", "snorkel"],
        "lat": 23.550,
        "lon": 119.590,
        "cwa_marine_zone": "澎湖海面",
        "cwa_tide_station": "澎湖縣馬公市",
    },
    {
        "slug": "penghu-south",
        "name": "澎湖南方四島",
        "name_en": "South Penghu Marine National Park",
        "region": "澎湖 · 南方四島",
        "blurb": "全台唯一的海洋國家公園，珊瑚礁覆蓋率極高，須搭船前往，潛季約四月到九月中。",
        "spots": ["東嶼坪嶼", "西吉嶼", "東吉嶼"],
        "activities": ["scuba", "freedive"],
        "lat": 23.256,
        "lon": 119.500,
        "cwa_marine_zone": "澎湖海面",
        "cwa_tide_station": "澎湖縣望安鄉",
    },
    {
        "slug": "yilan",
        "name": "宜蘭",
        "name_en": "Yilan",
        "region": "宜蘭 · 頭城 – 蘇澳",
        "blurb": "北台灣有浪頻率最高的一段海岸，烏石港三、四個點都能下浪，全年有浪。",
        "spots": ["烏石港北堤", "烏石港南堤", "外澳雙獅", "蜜月灣", "無尾港"],
        "activities": ["surf"],
        "lat": 24.876,
        "lon": 121.840,
        "cwa_marine_zone": "臺灣東北部海面",
        "cwa_tide_station": "宜蘭縣頭城鎮",
    },
    {
        "slug": "taitung",
        "name": "台東海岸",
        "name_en": "Taitung Coast",
        "region": "臺東 · 東河一帶",
        "blurb": "面對太平洋、鵝卵石海底，東北季風帶來穩定的好浪，金樽是 WSL 資格賽場地。",
        "spots": ["金樽", "東河", "都蘭"],
        "activities": ["surf"],
        "lat": 22.955,
        "lon": 121.295,
        "cwa_marine_zone": "臺灣東南部海面",
        "cwa_tide_station": "臺東縣臺東市",
    },
    {
        "slug": "miaoli",
        "name": "苗栗 · 竹南",
        "name_en": "Miaoli / Zhunan",
        "region": "苗栗 · 竹南",
        "blurb": "中部新興的入門浪點，海面相對平靜，適合初學者練習。",
        "spots": ["假日之森"],
        "activities": ["surf"],
        "lat": 24.699,
        "lon": 120.856,
        "cwa_marine_zone": "臺灣海峽中部",
        "cwa_tide_station": "苗栗縣竹南鎮",
    },
    {
        "slug": "tainan",
        "name": "台南 · 漁光島",
        "name_en": "Tainan / Yuguang Island",
        "region": "臺南 · 安平",
        "blurb": "市區 15 分鐘可達，浪型軟、厚，長短板練技術都合適。",
        "spots": ["漁光島"],
        "activities": ["surf"],
        "lat": 22.981,
        "lon": 120.156,
        "cwa_marine_zone": "臺灣海峽南部",
        "cwa_tide_station": "臺南市安平區",
    },
    {
        "slug": "kaohsiung",
        "name": "高雄 · 旗津",
        "name_en": "Kaohsiung / Qijin",
        "region": "高雄 · 旗津",
        "blurb": "高雄唯一的沙洲島，長海岸線，夏季西南氣流有浪、冬季較適合新手。",
        "spots": ["旗津"],
        "activities": ["surf"],
        "lat": 22.607,
        "lon": 120.269,
        "cwa_marine_zone": "臺灣海峽南部",
        "cwa_tide_station": "高雄市",
    },
]

# ─────────────────────────────  子潛點 / 浪點  ─────────────────────────────
# location = 上面 LOCATIONS 的 slug

SPOTS: list[dict] = [
    # ---- 小琉球 ----
    {"location": "xiaoliuqiu", "slug": "xiaoliuqiu-huapingyan", "name": "花瓶岩", "name_en": "Vase Rock",
     "lat": 22.355676, "lon": 120.380725, "coord_approx": False,
     "activities": ["scuba", "freedive", "snorkel"], "bottom": "reef", "shelter": "semi",
     "level": "beginner", "entry": "shore", "facing_deg": 350,
     "depth_min_m": 2, "depth_max_m": 12,
     "blurb": "小琉球最著名的下水點，珊瑚、熱帶魚與海龜密度高，浮潛體驗潛的大本營。"},
    {"location": "xiaoliuqiu", "slug": "xiaoliuqiu-meirendong", "name": "美人洞", "name_en": "Beauty Cave",
     "lat": 22.353339, "lon": 120.372572, "coord_approx": False,
     "activities": ["scuba", "freedive", "snorkel"], "bottom": "reef", "shelter": "semi",
     "level": "beginner", "entry": "shore", "facing_deg": 300,
     "depth_min_m": 3, "depth_max_m": 15,
     "blurb": "西北岸，能見度通常較好，遇到海龜的機率高。"},
    {"location": "xiaoliuqiu", "slug": "xiaoliuqiu-houshi", "name": "厚石裙礁", "name_en": "Houshi Fringing Reef",
     "lat": 22.325272, "lon": 120.365980, "coord_approx": False,
     "activities": ["scuba", "freedive"], "bottom": "reef", "shelter": "open",
     "level": "intermediate", "entry": "shore", "facing_deg": 135,
     "depth_min_m": 3, "depth_max_m": 18,
     "blurb": "東南岸的裙礁地形，開闊、偶有流，適合有一點經驗的人。"},
    {"location": "xiaoliuqiu", "slug": "xiaoliuqiu-longxiadong", "name": "龍蝦洞", "name_en": "Lobster Cave",
     "lat": 22.344980, "lon": 120.388293, "coord_approx": False,
     "activities": ["scuba", "freedive"], "bottom": "reef", "shelter": "open",
     "level": "intermediate", "entry": "shore", "facing_deg": 90,
     "depth_min_m": 4, "depth_max_m": 20,
     "blurb": "地形漂亮但東向、流較明顯，下水前要確認流況。"},
    {"location": "xiaoliuqiu", "slug": "xiaoliuqiu-shanfu", "name": "杉福漁港（沈船）", "name_en": "Shanfu Wreck",
     "lat": 22.340674, "lon": 120.362815, "coord_approx": True,
     "activities": ["scuba"], "bottom": "wreck", "shelter": "semi",
     "level": "intermediate", "entry": "shore", "facing_deg": 270,
     "depth_min_m": 12, "depth_max_m": 22,
     "blurb": "港外約 20 公尺深的沈船，需有經驗的嚮導帶。座標為港口位置，沈船在港外。"},

    # ---- 綠島 ----
    {"location": "lyudao", "slug": "lyudao-shilang", "name": "石朗", "name_en": "Shilang",
     "lat": 22.655427, "lon": 121.474854, "coord_approx": False,
     "activities": ["scuba", "freedive", "snorkel"], "bottom": "reef", "shelter": "semi",
     "level": "beginner", "entry": "shore", "facing_deg": 260,
     "depth_min_m": 5, "depth_max_m": 18,
     "blurb": "綠島最熱門的岸潛點，有名的海馬郵筒與大群熱帶魚，人多。"},
    {"location": "lyudao", "slug": "lyudao-chaikou", "name": "柴口", "name_en": "Chaikou",
     "lat": 22.677032, "lon": 121.484617, "coord_approx": True,
     "activities": ["scuba", "freedive", "snorkel"], "bottom": "reef", "shelter": "semi",
     "level": "beginner", "entry": "shore", "facing_deg": 0,
     "depth_min_m": 3, "depth_max_m": 15,
     "blurb": "北岸，壯麗的石珊瑚景觀、深淺有層次，大魚群常見。座標為附近陸上位置。"},
    {"location": "lyudao", "slug": "lyudao-dabaisha", "name": "大白沙", "name_en": "Dabaisha",
     "lat": 22.638026, "lon": 121.493891, "coord_approx": False,
     "activities": ["scuba", "freedive"], "bottom": "reef", "shelter": "open",
     "level": "intermediate", "entry": "shore", "facing_deg": 170,
     "depth_min_m": 5, "depth_max_m": 25,
     "blurb": "南岸，沿岸很快就超過 20 公尺，能見度佳但開闊、需注意流。"},
    {"location": "lyudao", "slug": "lyudao-daxianggu", "name": "大香菇", "name_en": "The Big Mushroom",
     "lat": 22.658, "lon": 121.470, "coord_approx": True,
     "activities": ["scuba"], "bottom": "reef", "shelter": "open",
     "level": "intermediate", "entry": "boat", "facing_deg": 260,
     "depth_min_m": 15, "depth_max_m": 20,
     "blurb": "石朗外海的巨大微孔珊瑚，根部約 18 公尺深。座標為推估。"},
    {"location": "lyudao", "slug": "lyudao-gangtiejiao", "name": "鋼鐵礁", "name_en": "Steel Reef",
     "lat": 22.645, "lon": 121.498, "coord_approx": True,
     "activities": ["scuba"], "bottom": "artificial", "shelter": "open",
     "level": "intermediate", "entry": "boat", "facing_deg": 150,
     "depth_min_m": 20, "depth_max_m": 30,
     "blurb": "龜灣與大白沙之間的人工魚礁，較深的船潛點。座標為推估。"},

    # ---- 蘭嶼 ----
    {"location": "lanyu", "slug": "lanyu-yunuyan", "name": "玉女岩", "name_en": "Yunu Rock",
     "lat": 22.080287, "lon": 121.517387, "coord_approx": False,
     "activities": ["scuba", "freedive"], "bottom": "reef", "shelter": "open",
     "level": "intermediate", "entry": "shore", "facing_deg": 350,
     "depth_min_m": 5, "depth_max_m": 25,
     "blurb": "朗島（北岸）一帶熱門的地形潛點，地貌豐富。"},
    {"location": "lanyu", "slug": "lanyu-mujiyan", "name": "母雞岩", "name_en": "Hen Rock",
     "lat": 22.083, "lon": 121.522, "coord_approx": True,
     "activities": ["scuba", "freedive"], "bottom": "reef", "shelter": "open",
     "level": "intermediate", "entry": "shore", "facing_deg": 10,
     "depth_min_m": 5, "depth_max_m": 25,
     "blurb": "朗島一帶的另一個地形點，與玉女岩相鄰。座標為推估。"},
    {"location": "lanyu", "slug": "lanyu-kaiyuan", "name": "開元港藍洞", "name_en": "Kaiyuan Blue Cave",
     "lat": 22.058448, "lon": 121.508244, "coord_approx": False,
     "activities": ["freedive", "scuba"], "bottom": "reef", "shelter": "semi",
     "level": "advanced", "entry": "shore", "facing_deg": 280,
     "depth_min_m": 3, "depth_max_m": 20,
     "blurb": "西岸，自由潛水的熱門洞穴地形，需具洞穴經驗與良好狀況。"},
    {"location": "lanyu", "slug": "lanyu-yeyou", "name": "椰油斷層", "name_en": "Yeyou Drop-off",
     "lat": 22.055, "lon": 121.512, "coord_approx": True,
     "activities": ["scuba"], "bottom": "reef", "shelter": "open",
     "level": "advanced", "entry": "shore", "facing_deg": 280,
     "depth_min_m": 10, "depth_max_m": 40,
     "blurb": "西岸的海底斷崖，落差超過 30 公尺，適合進階深潛。座標為推估。"},
    {"location": "lanyu", "slug": "lanyu-badaiwan", "name": "八代灣沈船", "name_en": "Badai Bay Wreck",
     "lat": 22.024753, "lon": 121.553437, "coord_approx": True,
     "activities": ["scuba"], "bottom": "wreck", "shelter": "open",
     "level": "advanced", "entry": "boat", "facing_deg": 180,
     "depth_min_m": 20, "depth_max_m": 40,
     "blurb": "南岸的沈船，船身約 40 公尺、桅桿約 20 公尺，流強，難度極高。座標為推估。"},

    # ---- 墾丁 · 恆春半島 ----
    {"location": "kenting-houbihu", "slug": "kenting-houbihu-spot", "name": "後壁湖", "name_en": "Houbihu",
     "lat": 21.9455, "lon": 120.7466, "coord_approx": True,
     "activities": ["scuba", "freedive", "snorkel"], "bottom": "harbour", "shelter": "sheltered",
     "level": "beginner", "entry": "shore", "facing_deg": 200,
     "depth_min_m": 3, "depth_max_m": 18,
     "blurb": "交通最方便的潛點，出水口海洋資源保護示範區內魚群密集，適合體驗潛水與教學。"},
    {"location": "kenting-houbihu", "slug": "kenting-chushuikou", "name": "出水口", "name_en": "Chushuikou",
     "lat": 21.943, "lon": 120.752, "coord_approx": True,
     "activities": ["scuba", "freedive"], "bottom": "reef", "shelter": "open",
     "level": "intermediate", "entry": "shore", "facing_deg": 180,
     "depth_min_m": 5, "depth_max_m": 20,
     "blurb": "火成岩地形，火焰貝與比目魚常見，但流較明顯。座標為推估。"},
    {"location": "kenting-houbihu", "slug": "kenting-wanlitong", "name": "萬里桐", "name_en": "Wanlitong",
     "lat": 21.997553, "lon": 120.704664, "coord_approx": False,
     "activities": ["scuba", "freedive", "snorkel"], "bottom": "reef", "shelter": "semi",
     "level": "beginner", "entry": "shore", "facing_deg": 270,
     "depth_min_m": 2, "depth_max_m": 15,
     "blurb": "西岸，珊瑚與魚群豐富、坡度平緩，適合入門與浮潛。"},
    {"location": "kenting-houbihu", "slug": "kenting-nanwan-e", "name": "南灣（東側 · 沙）", "name_en": "Nanwan East (sand)",
     "lat": 21.959257, "lon": 120.762902, "coord_approx": False,
     "activities": ["surf"], "bottom": "sand", "shelter": "semi",
     "level": "beginner", "entry": "shore", "facing_deg": 190,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "面對南灣偏左（東側）為沙底，浪型和緩，南部新手最愛的練習點。"},
    {"location": "kenting-houbihu", "slug": "kenting-nanwan-w", "name": "南灣（西側 · 礁）", "name_en": "Nanwan West (reef)",
     "lat": 21.959123, "lon": 120.760953, "coord_approx": False,
     "activities": ["surf"], "bottom": "reef", "shelter": "semi",
     "level": "advanced", "entry": "shore", "facing_deg": 195,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "面對南灣偏右（西側）礁岩較多，浪較有力，適合進階。"},
    {"location": "kenting-houbihu", "slug": "kenting-jialeshui", "name": "佳樂水", "name_en": "Jialeshui",
     "lat": 21.993889, "lon": 120.863611, "coord_approx": False,
     "activities": ["surf"], "bottom": "mixed", "shelter": "open",
     "level": "intermediate", "entry": "shore", "facing_deg": 100,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "東岸沙+礁混合，冬季東北季風時常有好浪，四季皆可衝。"},

    # ---- 東北角 ----
    {"location": "longdong", "slug": "longdong-bay", "name": "龍洞灣", "name_en": "Longdong Bay",
     "lat": 25.118036, "lon": 121.920546, "coord_approx": False,
     "activities": ["scuba", "freedive"], "bottom": "reef", "shelter": "sheltered",
     "level": "beginner", "entry": "shore", "facing_deg": 90,
     "depth_min_m": 3, "depth_max_m": 18,
     "blurb": "四稜砂岩地形、灣內平靜，是北台灣潛水課與自潛練習的主場。"},
    {"location": "longdong", "slug": "longdong-bitou", "name": "鼻頭角", "name_en": "Bitou Cape",
     "lat": 25.121500, "lon": 121.916781, "coord_approx": False,
     "activities": ["scuba", "freedive"], "bottom": "reef", "shelter": "open",
     "level": "intermediate", "entry": "shore", "facing_deg": 45,
     "depth_min_m": 5, "depth_max_m": 20,
     "blurb": "海蝕地形豐富，較開闊、東北向，浪與流比龍洞灣明顯。"},
    {"location": "longdong", "slug": "longdong-hemei", "name": "和美", "name_en": "Hemei",
     "lat": 25.113, "lon": 121.923, "coord_approx": True,
     "activities": ["scuba", "freedive"], "bottom": "reef", "shelter": "semi",
     "level": "intermediate", "entry": "shore", "facing_deg": 100,
     "depth_min_m": 5, "depth_max_m": 25,
     "blurb": "龍洞南側，深溝地形，適合有一點經驗的人。座標為推估。"},
    {"location": "longdong", "slug": "longdong-fulong", "name": "福隆", "name_en": "Fulong",
     "lat": 25.022245, "lon": 121.942755, "coord_approx": False,
     "activities": ["surf"], "bottom": "rivermouth", "shelter": "open",
     "level": "beginner", "entry": "shore", "facing_deg": 45,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "雙溪河口的沙灘，向右跑的浪，適合初學者。"},

    # ---- 北海岸 ----
    {"location": "beihaian", "slug": "beihaian-chaojing", "name": "潮境公園", "name_en": "Chaojing Park",
     "lat": 25.143411, "lon": 121.803391, "coord_approx": False,
     "activities": ["scuba", "freedive", "snorkel"], "bottom": "reef", "shelter": "semi",
     "level": "beginner", "entry": "shore", "facing_deg": 0,
     "depth_min_m": 2, "depth_max_m": 15,
     "blurb": "復育有成、生態豐富的岸潛點，週末人潮多。"},
    {"location": "beihaian", "slug": "beihaian-wanghaixiang", "name": "望海巷", "name_en": "Wanghaixiang",
     "lat": 25.137785, "lon": 121.803761, "coord_approx": False,
     "activities": ["scuba", "freedive", "snorkel"], "bottom": "reef", "shelter": "semi",
     "level": "beginner", "entry": "shore", "facing_deg": 0,
     "depth_min_m": 2, "depth_max_m": 12,
     "blurb": "潮境保育區的一部分，大量軟珊瑚。"},
    {"location": "beihaian", "slug": "beihaian-guihou", "name": "龜吼", "name_en": "Guihou",
     "lat": 25.195605, "lon": 121.688765, "coord_approx": False,
     "activities": ["scuba", "freedive", "snorkel"], "bottom": "mixed", "shelter": "semi",
     "level": "beginner", "entry": "shore", "facing_deg": 350,
     "depth_min_m": 2, "depth_max_m": 8,
     "blurb": "沿岸僅約 5 公尺深、熱帶魚多，適合浮潛與入門。"},
    {"location": "beihaian", "slug": "beihaian-baishawan", "name": "白沙灣", "name_en": "Baishawan",
     "lat": 25.284803, "lon": 121.514768, "coord_approx": False,
     "activities": ["surf"], "bottom": "sand", "shelter": "open",
     "level": "beginner", "entry": "shore", "facing_deg": 350,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "北海岸的沙灘浪點，吃北 / 東北湧浪，適合初學者。"},
    {"location": "beihaian", "slug": "beihaian-zhongjiao", "name": "中角灣", "name_en": "Zhongjiao Bay",
     "lat": 25.240807, "lon": 121.633381, "coord_approx": False,
     "activities": ["surf"], "bottom": "point", "shelter": "semi",
     "level": "beginner", "entry": "shore", "facing_deg": 10,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "離台北最近的浪點，全年有浪，衝浪學校聚集。"},

    # ---- 澎湖本島 ----
    {"location": "penghu", "slug": "penghu-shanshui", "name": "山水", "name_en": "Shanshui",
     "lat": 23.512555, "lon": 119.595106, "coord_approx": False,
     "activities": ["scuba", "freedive", "snorkel"], "bottom": "reef", "shelter": "semi",
     "level": "beginner", "entry": "shore", "facing_deg": 200,
     "depth_min_m": 2, "depth_max_m": 12,
     "blurb": "澎湖本島交通最方便的下水點，適合浮潛與體驗潛水。"},
    {"location": "penghu", "slug": "penghu-hangwan", "name": "杭灣", "name_en": "Hangwan",
     "lat": 23.505, "lon": 119.593, "coord_approx": True,
     "activities": ["scuba", "freedive", "snorkel"], "bottom": "reef", "shelter": "semi",
     "level": "beginner", "entry": "shore", "facing_deg": 200,
     "depth_min_m": 2, "depth_max_m": 12,
     "blurb": "山水沙灘旁的珊瑚礁灣，部分行程主打海底郵筒。座標為推估。"},

    # ---- 澎湖南方四島 ----
    {"location": "penghu-south", "slug": "psi-dongyuping", "name": "東嶼坪嶼", "name_en": "Dongyuping Islet",
     "lat": 23.256, "lon": 119.502, "coord_approx": True,
     "activities": ["scuba", "freedive"], "bottom": "reef", "shelter": "open",
     "level": "intermediate", "entry": "boat", "facing_deg": 135,
     "depth_min_m": 5, "depth_max_m": 25,
     "blurb": "玄武岩方山地形，珊瑚覆蓋率極高，東側巨石礁、五米礁地形變化豐富，水流稍強。座標為推估。"},
    {"location": "penghu-south", "slug": "psi-xiji", "name": "西吉嶼", "name_en": "Xiji Islet",
     "lat": 23.258, "lon": 119.482, "coord_approx": True,
     "activities": ["scuba", "freedive"], "bottom": "reef", "shelter": "open",
     "level": "intermediate", "entry": "boat", "facing_deg": 180,
     "depth_min_m": 5, "depth_max_m": 25,
     "blurb": "南側珊瑚礁遍佈，大型花環肉質軟珊瑚成群。座標為推估。"},
    {"location": "penghu-south", "slug": "psi-dongji", "name": "東吉嶼", "name_en": "Dongji Islet",
     "lat": 23.257, "lon": 119.665, "coord_approx": True,
     "activities": ["scuba", "freedive"], "bottom": "reef", "shelter": "open",
     "level": "intermediate", "entry": "boat", "facing_deg": 135,
     "depth_min_m": 5, "depth_max_m": 25,
     "blurb": "南方四島中面積較大的一座，周邊礁區與洋流帶來豐富魚況。座標為推估。"},

    # ---- 宜蘭（衝浪） ----
    {"location": "yilan", "slug": "yilan-wushi-n", "name": "烏石港北堤", "name_en": "Wushi Harbour North",
     "lat": 24.87066, "lon": 121.835885, "coord_approx": False,
     "activities": ["surf"], "bottom": "rivermouth", "shelter": "semi",
     "level": "beginner", "entry": "shore", "facing_deg": 45,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "北堤浪型和緩、人潮多，宜蘭最經典的新手浪點。"},
    {"location": "yilan", "slug": "yilan-wushi-s", "name": "烏石港南堤", "name_en": "Wushi Harbour South",
     "lat": 24.866, "lon": 121.838, "coord_approx": True,
     "activities": ["surf"], "bottom": "rivermouth", "shelter": "open",
     "level": "advanced", "entry": "shore", "facing_deg": 70,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "南堤浪較大、較有力，適合進階。座標為推估。"},
    {"location": "yilan", "slug": "yilan-waiao", "name": "外澳雙獅", "name_en": "Wai'ao",
     "lat": 24.879167, "lon": 121.842632, "coord_approx": False,
     "activities": ["surf"], "bottom": "sand", "shelter": "open",
     "level": "beginner", "entry": "shore", "facing_deg": 80,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "面對龜山島的沙灘，交通方便，初中階都適合。"},
    {"location": "yilan", "slug": "yilan-miyuewan", "name": "蜜月灣", "name_en": "Honeymoon Bay",
     "lat": 24.93173, "lon": 121.885735, "coord_approx": False,
     "activities": ["surf"], "bottom": "reef", "shelter": "open",
     "level": "intermediate", "entry": "shore", "facing_deg": 90,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "新月形海灣、礁石浪，浪況好時很有力，中高階。"},
    {"location": "yilan", "slug": "yilan-wuweigang", "name": "無尾港", "name_en": "Wuweigang",
     "lat": 24.641, "lon": 121.847, "coord_approx": True,
     "activities": ["surf"], "bottom": "sand", "shelter": "open",
     "level": "beginner", "entry": "shore", "facing_deg": 90,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "蘇澳一帶的沙灘浪點，人較少。座標為推估。"},

    # ---- 台東海岸（衝浪） ----
    {"location": "taitung", "slug": "taitung-jinzun", "name": "金樽", "name_en": "Jinzun",
     "lat": 22.954203, "lon": 121.292328, "coord_approx": False,
     "activities": ["surf"], "bottom": "point", "shelter": "open",
     "level": "advanced", "entry": "shore", "facing_deg": 80,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "台灣最好的浪點之一，鵝卵石海底、管浪，WSL 資格賽場地，進階以上。"},
    {"location": "taitung", "slug": "taitung-donghe", "name": "東河", "name_en": "Donghe",
     "lat": 22.968, "lon": 121.311, "coord_approx": True,
     "activities": ["surf"], "bottom": "rivermouth", "shelter": "open",
     "level": "beginner", "entry": "shore", "facing_deg": 90,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "浪質與頻率最穩定的地方，南段礁、北段適合長板。座標為河口推估。"},
    {"location": "taitung", "slug": "taitung-dulan", "name": "都蘭", "name_en": "Dulan",
     "lat": 22.879, "lon": 121.238, "coord_approx": True,
     "activities": ["surf"], "bottom": "reef", "shelter": "open",
     "level": "intermediate", "entry": "shore", "facing_deg": 100,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "都蘭鼻一帶的礁石浪，藝文聚落旁。座標為推估。"},

    # ---- 苗栗 / 台南 / 高雄（衝浪） ----
    {"location": "miaoli", "slug": "miaoli-jiarizhisen", "name": "假日之森", "name_en": "Holiday Forest",
     "lat": 24.699, "lon": 120.856, "coord_approx": True,
     "activities": ["surf"], "bottom": "sand", "shelter": "open",
     "level": "beginner", "entry": "shore", "facing_deg": 290,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "竹南濱海森林遊憩區旁的沙灘，海面平靜，適合初學。座標為推估。"},
    {"location": "tainan", "slug": "tainan-yuguang", "name": "漁光島", "name_en": "Yuguang Island",
     "lat": 22.98143, "lon": 120.15642, "coord_approx": False,
     "activities": ["surf"], "bottom": "sand", "shelter": "open",
     "level": "beginner", "entry": "shore", "facing_deg": 250,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "軟浪、厚浪，長短板練技術都合適，市區 15 分鐘可達。"},
    {"location": "kaohsiung", "slug": "kaohsiung-qijin", "name": "旗津", "name_en": "Qijin",
     "lat": 22.607121, "lon": 120.269077, "coord_approx": False,
     "activities": ["surf"], "bottom": "sand", "shelter": "open",
     "level": "beginner", "entry": "shore", "facing_deg": 250,
     "depth_min_m": None, "depth_max_m": None,
     "blurb": "高雄唯一的沙洲島，長沙灘，夏季西南氣流有浪。"},
]
